# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `closure_tree` gem.
# Please instead update this file by running `bin/tapioca gem closure_tree`.


# This class and mixins are an effort to reduce the namespace pollution to models that act_as_tree.
#
# source://closure_tree//lib/closure_tree.rb#10
module ClosureTree
  class << self
    # source://closure_tree//lib/closure_tree.rb#11
    def configure; end
  end
end

# source://closure_tree//lib/closure_tree/active_record_support.rb#4
module ClosureTree::ActiveRecordSupport
  # source://closure_tree//lib/closure_tree/active_record_support.rb#5
  def quote(*_arg0, **_arg1, &_arg2); end

  # source://closure_tree//lib/closure_tree/active_record_support.rb#7
  def remove_prefix_and_suffix(table_name, model = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/arel_helpers.rb#4
module ClosureTree::ArelHelpers
  # Helper to create an Arel node for a table with an alias
  #
  # source://closure_tree//lib/closure_tree/arel_helpers.rb#32
  def aliased_table(table, alias_name); end

  # source://closure_tree//lib/closure_tree/arel_helpers.rb#60
  def build_hierarchy_delete_query(hierarchy_table, id); end

  # Build Arel queries for hierarchy operations
  #
  # source://closure_tree//lib/closure_tree/arel_helpers.rb#37
  def build_hierarchy_insert_query(hierarchy_table, node_id, parent_id); end

  # Get hierarchy table using the model_class
  # This is for Support class methods
  #
  # source://closure_tree//lib/closure_tree/arel_helpers.rb#24
  def hierarchy_table; end

  # Get hierarchy table from a model class
  # This method should be called from instance methods where hierarchy_class is available
  #
  # source://closure_tree//lib/closure_tree/arel_helpers.rb#12
  def hierarchy_table_for(model); end

  # Get model's arel table
  #
  # source://closure_tree//lib/closure_tree/arel_helpers.rb#6
  def model_table; end

  # Convert an Arel AST to SQL using the correct connection's visitor
  # This ensures proper quoting for the specific database adapter (MySQL uses backticks, PostgreSQL uses double quotes)
  #
  # source://closure_tree//lib/closure_tree/arel_helpers.rb#85
  def to_sql_with_connection(arel_manager); end
end

# This concern sets up the ActiveRecord associations after all other modules are included.
# It must be included last to ensure that HierarchyMaintenance callbacks are already set up.
#
# source://closure_tree//lib/closure_tree/association_setup.rb#8
module ClosureTree::AssociationSetup
  extend ::ActiveSupport::Concern
end

# Minimal configuration class to handle deprecated options
#
# source://closure_tree//lib/closure_tree/configuration.rb#5
class ClosureTree::Configuration
  # Keep the old method name for backward compatibility
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/configuration.rb#20
  def database_less; end

  # source://closure_tree//lib/closure_tree/configuration.rb#6
  def database_less=(_value); end

  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/configuration.rb#15
  def database_less?; end
end

# source://closure_tree//lib/closure_tree/deterministic_ordering.rb#4
module ClosureTree::DeterministicOrdering
  # source://closure_tree//lib/closure_tree/deterministic_ordering.rb#5
  def order_value; end

  # source://closure_tree//lib/closure_tree/deterministic_ordering.rb#13
  def order_value=(new_order_value); end

  # source://closure_tree//lib/closure_tree/deterministic_ordering.rb#21
  def siblings_after; end

  # source://closure_tree//lib/closure_tree/deterministic_ordering.rb#17
  def siblings_before; end

  # source://closure_tree//lib/closure_tree/deterministic_ordering.rb#9
  def update_order_value(order_value); end
end

# source://closure_tree//lib/closure_tree/digraphs.rb#4
module ClosureTree::Digraphs
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ClosureTree::Digraphs::ClassMethods

  # override this method in your model class if you want a different digraph label.
  #
  # source://closure_tree//lib/closure_tree/digraphs.rb#12
  def to_digraph_label; end

  # source://closure_tree//lib/closure_tree/digraphs.rb#7
  def to_dot_digraph; end
end

# source://closure_tree//lib/closure_tree/digraphs.rb#16
module ClosureTree::Digraphs::ClassMethods
  # source://closure_tree//lib/closure_tree/digraphs.rb#18
  def to_dot_digraph(tree_scope); end
end

# source://closure_tree//lib/closure_tree/finders.rb#4
module ClosureTree::Finders
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ClosureTree::Finders::ClassMethods

  # source://closure_tree//lib/closure_tree/finders.rb#39
  def find_all_by_generation(generation_level); end

  # Find a descendant node whose +ancestry_path+ will be ```self.ancestry_path + path```
  #
  # source://closure_tree//lib/closure_tree/finders.rb#8
  def find_by_path(path, attributes = T.unsafe(nil)); end

  # Find or create a descendant node whose +ancestry_path+ will be ```self.ancestry_path + path```
  #
  # source://closure_tree//lib/closure_tree/finders.rb#15
  def find_or_create_by_path(path, attributes = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/finders.rb#61
  def without_self(scope); end
end

# source://closure_tree//lib/closure_tree/finders.rb#65
module ClosureTree::Finders::ClassMethods
  # source://closure_tree//lib/closure_tree/finders.rb#143
  def find_all_by_generation(generation_level); end

  # source://closure_tree//lib/closure_tree/finders.rb#183
  def find_by_path(path, attributes = T.unsafe(nil), parent_id = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/finders.rb#207
  def find_or_create_by_path(path, attributes = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/finders.rb#83
  def leaves; end

  # source://closure_tree//lib/closure_tree/finders.rb#130
  def lowest_common_ancestor(*descendants); end

  # source://closure_tree//lib/closure_tree/finders.rb#79
  def root; end

  # source://closure_tree//lib/closure_tree/finders.rb#74
  def roots; end

  # source://closure_tree//lib/closure_tree/finders.rb#104
  def with_ancestor(*ancestors); end

  # source://closure_tree//lib/closure_tree/finders.rb#117
  def with_descendant(*descendants); end

  # source://closure_tree//lib/closure_tree/finders.rb#66
  def without_instance(instance); end
end

# source://closure_tree//lib/closure_tree/has_closure_tree.rb#4
module ClosureTree::HasClosureTree
  # Only alias acts_as_tree if it's not already defined (to avoid conflicts with other gems)
  #
  # source://closure_tree//lib/closure_tree/has_closure_tree.rb#47
  def acts_as_tree(options = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/has_closure_tree.rb#5
  def has_closure_tree(options = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/has_closure_tree_root.rb#7
module ClosureTree::HasClosureTreeRoot
  # source://closure_tree//lib/closure_tree/has_closure_tree_root.rb#8
  def has_closure_tree_root(assoc_name, options = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/hash_tree.rb#4
module ClosureTree::HashTree
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ClosureTree::HashTree::ClassMethods

  # source://closure_tree//lib/closure_tree/hash_tree.rb#7
  def hash_tree(options = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/hash_tree.rb#11
module ClosureTree::HashTree::ClassMethods
  # source://closure_tree//lib/closure_tree/hash_tree.rb#14
  def hash_tree(options = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/hash_tree_support.rb#4
module ClosureTree::HashTreeSupport
  # Builds nested hash structure using the scope returned from the passed in scope
  #
  # source://closure_tree//lib/closure_tree/hash_tree_support.rb#50
  def build_hash_tree(tree_scope); end

  # source://closure_tree//lib/closure_tree/hash_tree_support.rb#5
  def default_tree_scope(scope, limit_depth = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/hash_tree_support.rb#44
  def hash_tree(tree_scope, limit_depth = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#6
module ClosureTree::HierarchyMaintenance
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ClosureTree::HierarchyMaintenance::ClassMethods

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#40
  def _ct_after_save; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#53
  def _ct_before_destroy; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#35
  def _ct_before_save; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#16
  def _ct_skip_cycle_detection!; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#20
  def _ct_skip_sort_order_maintenance!; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#24
  def _ct_validate; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#101
  def delete_hierarchy_references; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#75
  def rebuild!(called_by_rebuild = T.unsafe(nil)); end

  private

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#62
  def _ct_adopt_children_to_grandparent; end
end

# source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#114
module ClosureTree::HierarchyMaintenance::ClassMethods
  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#125
  def cleanup!; end

  # source://closure_tree//lib/closure_tree/hierarchy_maintenance.rb#117
  def rebuild!; end
end

# source://closure_tree//lib/closure_tree/model.rb#6
module ClosureTree::Model
  extend ::ActiveSupport::Concern

  # Delegate to the Support instance on the class:
  #
  # source://closure_tree//lib/closure_tree/model.rb#10
  def _ct; end

  # source://closure_tree//lib/closure_tree/model.rb#141
  def _ct_id; end

  # source://closure_tree//lib/closure_tree/model.rb#133
  def _ct_parent_id; end

  # source://closure_tree//lib/closure_tree/model.rb#145
  def _ct_quoted_id; end

  # source://closure_tree//lib/closure_tree/model.rb#137
  def _ct_quoted_parent_id; end

  # Alias for appending to the children collection.
  # You can also add directly to the children collection, if you'd prefer.
  #
  # source://closure_tree//lib/closure_tree/model.rb#128
  def add_child(child_node); end

  # source://closure_tree//lib/closure_tree/model.rb#51
  def ancestor_ids; end

  # node's ancestors include this record
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#107
  def ancestor_of?(node); end

  # enumerable of ancestors, immediate parent is first, root is last.
  #
  # source://closure_tree//lib/closure_tree/model.rb#47
  def ancestors; end

  # Returns an array, root first, of self_and_ancestors' values of the +to_s_column+, which defaults
  # to the +name_column+.
  # (so child.ancestry_path == +%w{grandparent parent child}+
  #
  # source://closure_tree//lib/closure_tree/model.rb#62
  def ancestry_path(to_s_column = T.unsafe(nil)); end

  # Returns true if this node has a parent, and is not a root.
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#22
  def child?; end

  # source://closure_tree//lib/closure_tree/model.rb#66
  def child_ids; end

  # node is record's parent
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#117
  def child_of?(node); end

  # source://closure_tree//lib/closure_tree/model.rb#40
  def depth; end

  # source://closure_tree//lib/closure_tree/model.rb#78
  def descendant_ids; end

  # node is record's ancestor
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#112
  def descendant_of?(node); end

  # source://closure_tree//lib/closure_tree/model.rb#70
  def descendants; end

  # node and record have a same root
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#122
  def family_of?(node); end

  # Returns true if this node has no children.
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#27
  def leaf?; end

  # source://closure_tree//lib/closure_tree/model.rb#36
  def leaves; end

  # source://closure_tree//lib/closure_tree/model.rb#44
  def level; end

  # node's parent is this record
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#97
  def parent_of?(node); end

  # Returns the farthest ancestor, or self if +root?+
  #
  # source://closure_tree//lib/closure_tree/model.rb#32
  def root; end

  # Returns true if this node has no parents.
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#15
  def root?; end

  # node's root is this record
  #
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/model.rb#102
  def root_of?(node); end

  # source://closure_tree//lib/closure_tree/model.rb#55
  def self_and_ancestors_ids; end

  # source://closure_tree//lib/closure_tree/model.rb#74
  def self_and_descendant_ids; end

  # source://closure_tree//lib/closure_tree/model.rb#82
  def self_and_siblings; end

  # source://closure_tree//lib/closure_tree/model.rb#92
  def sibling_ids; end

  # source://closure_tree//lib/closure_tree/model.rb#88
  def siblings; end
end

# source://closure_tree//lib/closure_tree/has_closure_tree_root.rb#4
class ClosureTree::MultipleRootError < ::StandardError; end

# source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#7
module ClosureTree::NumericDeterministicOrdering
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ClosureTree::NumericDeterministicOrdering::ClassMethods

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#28
  def _ct_reorder_children(minimum_sort_order_value = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#14
  def _ct_reorder_prior_siblings_if_parent_changed; end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#22
  def _ct_reorder_siblings(minimum_sort_order_value = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#152
  def add_sibling(sibling, add_after = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#128
  def append_child(child_node); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#144
  def append_sibling(sibling_node); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#132
  def prepend_child(child_node); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#148
  def prepend_sibling(sibling_node); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#33
  def self_and_descendants_preordered; end
end

# source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#65
module ClosureTree::NumericDeterministicOrdering::ClassMethods
  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#67
  def _ct_sum_order_by(node = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/numeric_deterministic_ordering.rb#90
  def roots_and_descendants_preordered; end
end

# source://closure_tree//lib/closure_tree/numeric_order_support.rb#4
module ClosureTree::NumericOrderSupport
  class << self
    # source://closure_tree//lib/closure_tree/numeric_order_support.rb#5
    def adapter_for_connection(connection); end
  end
end

# source://closure_tree//lib/closure_tree/numeric_order_support.rb#68
module ClosureTree::NumericOrderSupport::GenericAdapter
  # source://closure_tree//lib/closure_tree/numeric_order_support.rb#69
  def reorder_with_parent_id(parent_id, minimum_sort_order_value = T.unsafe(nil), scope_conditions = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/numeric_order_support.rb#16
module ClosureTree::NumericOrderSupport::MysqlAdapter
  # source://closure_tree//lib/closure_tree/numeric_order_support.rb#17
  def reorder_with_parent_id(parent_id, minimum_sort_order_value = T.unsafe(nil), scope_conditions = T.unsafe(nil)); end
end

# source://closure_tree//lib/closure_tree/numeric_order_support.rb#38
module ClosureTree::NumericOrderSupport::PostgreSQLAdapter
  # source://closure_tree//lib/closure_tree/numeric_order_support.rb#39
  def reorder_with_parent_id(parent_id, minimum_sort_order_value = T.unsafe(nil), scope_conditions = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/numeric_order_support.rb#63
  def rows_updated(result); end
end

# source://closure_tree//lib/closure_tree/has_closure_tree_root.rb#5
class ClosureTree::RootOrderingDisabledError < ::StandardError; end

# source://closure_tree//lib/closure_tree/support.rb#5
class ClosureTree::Support
  include ::ClosureTree::SupportFlags
  include ::ClosureTree::SupportAttributes
  include ::ClosureTree::ActiveRecordSupport
  include ::ClosureTree::HashTreeSupport
  include ::ClosureTree::ArelHelpers

  # @raise [ArgumentError]
  # @return [Support] a new instance of Support
  #
  # source://closure_tree//lib/closure_tree/support.rb#14
  def initialize(model_class, options); end

  # Find the abstract base class for database connection
  # This ensures hierarchy class uses the same database but doesn't inherit
  # validations/callbacks from STI parent classes (issue #392)
  #
  # source://closure_tree//lib/closure_tree/support.rb#41
  def abstract_base_class; end

  # source://closure_tree//lib/closure_tree/support.rb#254
  def apply_scope_conditions(scope, instance = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/support.rb#165
  def build_ancestry_attr_path(path, attributes); end

  # Builds SQL WHERE conditions for scope columns
  # Returns a string that can be appended to a WHERE clause
  #
  # source://closure_tree//lib/closure_tree/support.rb#141
  def build_scope_where_clause(scope_conditions); end

  # source://closure_tree//lib/closure_tree/support.rb#209
  def create(model_class, attributes); end

  # source://closure_tree//lib/closure_tree/support.rb#213
  def create!(model_class, attributes); end

  # source://closure_tree//lib/closure_tree/support.rb#201
  def creator_class(model_class, sti_class); end

  # source://closure_tree//lib/closure_tree/support.rb#189
  def find_by_large_path(path, attributes = T.unsafe(nil), parent_id = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/support.rb#119
  def has_many_order_with_option(order_by_opt = T.unsafe(nil)); end

  # lambda-ize the order, but don't apply the default order_option
  #
  # source://closure_tree//lib/closure_tree/support.rb#115
  def has_many_order_without_option(order_by_opt); end

  # source://closure_tree//lib/closure_tree/support.rb#54
  def hierarchy_class_for_model; end

  # source://closure_tree//lib/closure_tree/support.rb#80
  def hierarchy_table_name; end

  # source://closure_tree//lib/closure_tree/support.rb#127
  def ids_from(scope); end

  # source://closure_tree//lib/closure_tree/support.rb#184
  def max_join_tables; end

  # Returns the value of attribute model_class.
  #
  # source://closure_tree//lib/closure_tree/support.rb#12
  def model_class; end

  # Returns the value of attribute options.
  #
  # source://closure_tree//lib/closure_tree/support.rb#12
  def options; end

  # source://closure_tree//lib/closure_tree/support.rb#217
  def scope_columns; end

  # source://closure_tree//lib/closure_tree/support.rb#232
  def scope_values_from_instance(instance); end

  # source://closure_tree//lib/closure_tree/support.rb#106
  def scope_with_order(scope, additional_order_by = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/support.rb#177
  def scoped_attributes(scope, attributes, target_table = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/support.rb#131
  def where_eq(column_name, value); end

  # source://closure_tree//lib/closure_tree/support.rb#155
  def with_advisory_lock(&block); end

  # source://closure_tree//lib/closure_tree/support.rb#101
  def with_order_option(opts); end
end

# source://closure_tree//lib/closure_tree/support_attributes.rb#7
module ClosureTree::SupportAttributes
  extend ::Forwardable

  # source://closure_tree//lib/closure_tree/support_attributes.rb#11
  def advisory_lock_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#9
  def base_class(*args, **_arg1, &block); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#9
  def column_names(*args, **_arg1, &block); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#9
  def connection(*args, **_arg1, &block); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#104
  def dont_order_roots; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#45
  def hierarchy_class_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#9
  def inheritance_column(*args, **_arg1, &block); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#65
  def name_column; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#69
  def name_sym; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#108
  def nulls_last_order_by; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#100
  def order_by; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#112
  def order_by_order(reverse = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#118
  def order_column; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#133
  def order_column_sym; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#57
  def parent_column_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#61
  def parent_column_sym; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#49
  def primary_key_column; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#53
  def primary_key_type; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#84
  def quoted_hierarchy_table_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#88
  def quoted_id_column_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#96
  def quoted_name_column; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#138
  def quoted_order_column(include_table_name = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#92
  def quoted_parent_column_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#37
  def quoted_table_name; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#41
  def quoted_value(value); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#129
  def require_order_column; end

  # Returns the constant name of the hierarchy_class
  #
  # @example
  #   Namespace::Model.hierarchy_class_name # => "Namespace::ModelHierarchy"
  #   Namespace::Model.short_hierarchy_class_name # => "ModelHierarchy"
  # @return [String] the constant name
  #
  # source://closure_tree//lib/closure_tree/support_attributes.rb#80
  def short_hierarchy_class_name; end

  # table_name alias keyword , like "AS". When used on table name alias, Oracle Database don't support used 'AS'
  #
  # source://closure_tree//lib/closure_tree/support_attributes.rb#145
  def t_alias_keyword; end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#9
  def table_name(*args, **_arg1, &block); end

  # source://closure_tree//lib/closure_tree/support_attributes.rb#9
  def transaction(*args, **_arg1, &block); end
end

# source://closure_tree//lib/closure_tree/support_flags.rb#4
module ClosureTree::SupportFlags
  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/support_flags.rb#17
  def has_inheritance_column?(hash = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/support_flags.rb#21
  def has_name?; end

  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/support_flags.rb#9
  def order_is_numeric?; end

  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/support_flags.rb#5
  def order_option?; end

  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/support_flags.rb#13
  def subclass?; end
end

# source://closure_tree//lib/closure_tree/test/matcher.rb#6
module ClosureTree::Test; end

# source://closure_tree//lib/closure_tree/test/matcher.rb#7
module ClosureTree::Test::Matcher
  # source://closure_tree//lib/closure_tree/test/matcher.rb#8
  def be_a_closure_tree; end
end

# source://closure_tree//lib/closure_tree/test/matcher.rb#12
class ClosureTree::Test::Matcher::ClosureTree
  # source://closure_tree//lib/closure_tree/test/matcher.rb#83
  def description; end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#71
  def failure_message; end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#75
  def failure_message_for_should; end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#81
  def failure_message_for_should_not; end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#77
  def failure_message_when_negated; end

  # @return [Boolean]
  #
  # source://closure_tree//lib/closure_tree/test/matcher.rb#13
  def matches?(subject); end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#55
  def ordered(column = T.unsafe(nil)); end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#61
  def with_advisory_lock; end

  # source://closure_tree//lib/closure_tree/test/matcher.rb#66
  def without_advisory_lock; end
end

# source://closure_tree//lib/closure_tree/version.rb#4
ClosureTree::VERSION = T.let(T.unsafe(nil), Gem::Version)
