# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `document_serializable` gem.
# Please instead update this file by running `bin/tapioca gem document_serializable`.

# source://document_serializable//lib/document_serializable/version.rb#1
module DocumentSerializable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::DocumentSerializable::ClassMethods
end

# source://document_serializable//lib/document_serializable.rb#0
module DocumentSerializable::ClassMethods
  # source://document_serializable//lib/document_serializable.rb#42
  def attribute(name, type = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://document_serializable//lib/document_serializable.rb#36
  def property_class; end
end

# source://document_serializable//lib/document_serializable/version.rb#2
DocumentSerializable::VERSION = T.let(T.unsafe(nil), String)
