# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `solargraph-standardrb` gem.
# Please instead update this file by running `bin/tapioca gem solargraph-standardrb`.

# source://solargraph-standardrb//lib/solargraph/standardrb/version.rb#1
module Solargraph
  class << self
    # source://solargraph/0.48.0/lib/solargraph.rb#53
    def logger; end

    # source://solargraph/0.48.0/lib/solargraph.rb#61
    def with_clean_env(&block); end
  end
end

# source://solargraph-standardrb//lib/solargraph/standardrb/version.rb#2
module Solargraph::Standardrb; end

# source://solargraph-standardrb//lib/solargraph-standardrb.rb#7
class Solargraph::Standardrb::Reporter < ::Solargraph::Diagnostics::Rubocop
  # source://solargraph-standardrb//lib/solargraph-standardrb.rb#8
  def diagnose(source, _api_map); end

  private

  # source://solargraph-standardrb//lib/solargraph-standardrb.rb#21
  def args(source); end
end

# source://solargraph-standardrb//lib/solargraph/standardrb/version.rb#3
Solargraph::Standardrb::VERSION = T.let(T.unsafe(nil), String)
