# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `translate_client` gem.
# Please instead update this file by running `bin/tapioca gem translate_client`.

# source://translate_client//lib/translate_client/version.rb#3
module TranslateClient; end

# source://translate_client//lib/translate_client/client.rb#2
class TranslateClient::Client
  # @return [Client] a new instance of Client
  #
  # source://translate_client//lib/translate_client/client.rb#8
  def initialize; end

  # Returns the value of attribute base_url.
  #
  # source://translate_client//lib/translate_client/client.rb#6
  def base_url; end

  # source://translate_client//lib/translate_client/client.rb#24
  def download; end

  # Returns the value of attribute locales.
  #
  # source://translate_client//lib/translate_client/client.rb#6
  def locales; end

  # source://translate_client//lib/translate_client/client.rb#35
  def sync; end

  # Returns the value of attribute token.
  #
  # source://translate_client//lib/translate_client/client.rb#6
  def token; end

  # source://translate_client//lib/translate_client/client.rb#13
  def upload; end

  private

  # source://translate_client//lib/translate_client/client.rb#42
  def locale_path(locale); end
end

# source://translate_client//lib/translate_client/client.rb#3
class TranslateClient::Client::Error < ::StandardError; end

# source://translate_client//lib/translate_client/client.rb#4
class TranslateClient::Client::NetworkError < ::TranslateClient::Client::Error; end

# source://translate_client//lib/translate_client.rb#8
class TranslateClient::Error < ::StandardError; end

# source://translate_client//lib/translate_client.rb#9
class TranslateClient::NetworkError < ::TranslateClient::Error; end

# source://translate_client//lib/translate_client/railtie.rb#2
class TranslateClient::Railtie < ::Rails::Railtie; end

# source://translate_client//lib/translate_client/version.rb#4
TranslateClient::VERSION = T.let(T.unsafe(nil), String)
