# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `with_advisory_lock` gem.
# Please instead update this file by running `bin/tapioca gem with_advisory_lock`.


# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
