# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yard-solargraph` gem.
# Please instead update this file by running `bin/tapioca gem yard-solargraph`.


# source://yard-solargraph//lib/yard/solargraph/version.rb#3
module YARD; end

# source://yard-solargraph//lib/yard/solargraph/version.rb#4
module YARD::Solargraph; end

# source://yard-solargraph//lib/yard/solargraph/version.rb#5
YARD::Solargraph::VERSION = T.let(T.unsafe(nil), String)
