AllCops:
  TargetRubyVersion: 3.3.2
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: disable
  Exclude:
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'

inherit_gem:
  shimmer: config/rubocop_base.yml

require:
  - rubocop-rspec_rails

# Metrics/AbcSize:
#   Enabled: false
#   Max: 9999 # for some reason, `Enabled: false` does not disable it 🤷🏼‍♂️
