AllCops:
  TargetRubyVersion: 3.1

inherit_gem:
  shimmer: config/rubocop_base.yml

# TODO: Sync with Shimmer
Style/TernaryParentheses:
  Enabled: false

# TODO: Sync with Shimmer
Metrics/AbcSize:
  Enabled: false
  Max: 9999 # for some reason, `Enabled: false` does not disable it 🤷🏼‍♂️
