# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Shimmer::FilesController`.
# Please instead update this file by running `bin/tapioca dsl Shimmer::FilesController`.

class Shimmer::FilesController
  sig { returns(HelperProxy) }
  def helpers; end

  module HelperMethods
    include ::ActionController::Base::HelperMethods
  end

  class HelperProxy < ::ActionView::Base
    include HelperMethods
  end
end
