# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Shimmer::SitemapJob`.
# Please instead update this file by running `bin/tapioca dsl Shimmer::SitemapJob`.

class Shimmer::SitemapJob
  class << self
    sig { returns(T.any(Shimmer::SitemapJob, FalseClass)) }
    def perform_later; end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
